"""Generate SLURM sbatch submission scripts from JobParameters.

Produces distinct resource directives for GPU vs CPU jobs per SLURM best
practices, and includes helpful section comments in the generated script.
"""

from __future__ import annotations

import os
import stat
from datetime import datetime

from job_assist.prompts import JobParameters


def generate_script(params: JobParameters) -> str:
    """Build a complete sbatch script string from job parameters."""
    lines: list[str] = []
    is_gpu = params.job_type == "gpu"

    lines.append(params.shell)
    lines.append(
        f"#  Generated by job-assist on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"
    )
    lines.append(
        f"#  Job type: {'GPU' if is_gpu else 'CPU'}"
    )
    lines.append("")

    # ── Job identification ──
    lines.append("# ── Job identification ──")
    lines.append(f"#SBATCH --job-name={params.job_name}")
    if params.account:
        lines.append(f"#SBATCH --account={params.account}")
    if params.partition:
        lines.append(f"#SBATCH --partition={params.partition}")
    if params.qos:
        lines.append(f"#SBATCH --qos={params.qos}")
    lines.append("")

    # ── Resources ──
    if is_gpu:
        lines.append("# ── GPU resources ──")
        lines.append(f"#SBATCH --gres={params.gres}")
        lines.append(f"#SBATCH --cpus-per-gpu={params.cpus_per_gpu}")
        if params.mem_per_gpu:
            lines.append(f"#SBATCH --mem-per-gpu={params.mem_per_gpu}")
    else:
        lines.append("# ── CPU resources ──")
        if params.nodes > 1:
            lines.append(f"#SBATCH --nodes={params.nodes}")
            if params.ntasks_per_node is not None:
                lines.append(f"#SBATCH --ntasks-per-node={params.ntasks_per_node}")
            elif params.ntasks > 1:
                lines.append(f"#SBATCH --ntasks={params.ntasks}")
        lines.append(f"#SBATCH --cpus-per-task={params.cpus_per_task}")
        if params.mem:
            lines.append(f"#SBATCH --mem={params.mem}")
        elif params.mem_per_cpu:
            lines.append(f"#SBATCH --mem-per-cpu={params.mem_per_cpu}")
    lines.append("")

    # ── Time ──
    lines.append("# ── Time limit ──")
    lines.append(f"#SBATCH --time={params.time}")
    lines.append("")

    # ── Output ──
    lines.append("# ── Output files ──")
    lines.append(f"#SBATCH --output={params.output}")
    lines.append(f"#SBATCH --error={params.error}")
    lines.append("")

    # ── Notifications ──
    if params.mail_type and params.mail_type != "NONE":
        lines.append("# ── Notifications ──")
        lines.append(f"#SBATCH --mail-user={params.mail_user}")
        lines.append(f"#SBATCH --mail-type={params.mail_type}")
        lines.append("")

    # ── Optional directives ──
    has_optional = any([
        params.constraint, params.exclusive, params.array,
        params.dependency, params.workdir, params.extra_sbatch_lines,
    ])
    if has_optional:
        lines.append("# ── Additional options ──")
        if params.constraint:
            lines.append(f"#SBATCH --constraint={params.constraint}")
        if params.exclusive:
            lines.append("#SBATCH --exclusive")
        if params.array:
            lines.append(f"#SBATCH --array={params.array}")
        if params.dependency:
            lines.append(f"#SBATCH --dependency={params.dependency}")
        if params.workdir:
            lines.append(f"#SBATCH --chdir={params.workdir}")
        for extra in params.extra_sbatch_lines:
            if not extra.startswith("#SBATCH"):
                extra = f"#SBATCH {extra}"
            lines.append(extra)
        lines.append("")

    # ── Environment setup ──
    lines.append("# ── Environment setup ──")
    lines.append("set -euo pipefail")
    lines.append("")

    lines.append('echo "Job $SLURM_JOB_ID started on $(hostname) at $(date)"')
    if is_gpu:
        lines.append(
            'echo "Partition: $SLURM_JOB_PARTITION |'
            ' GPUs: ${SLURM_GPUS_ON_NODE:-N/A} |'
            ' CPUs: $SLURM_CPUS_PER_TASK"'
        )
    else:
        lines.append(
            'echo "Partition: $SLURM_JOB_PARTITION |'
            ' Nodes: $SLURM_JOB_NUM_NODES |'
            ' CPUs: $SLURM_CPUS_PER_TASK"'
        )
    lines.append("")

    if params.modules:
        lines.append("module purge")
        for mod in params.modules:
            lines.append(f"module load {mod}")
        lines.append("")

    if params.conda_env:
        lines.append(
            'eval "$(conda shell.bash hook 2>/dev/null)" || '
            'source "$(conda info --base)/etc/profile.d/conda.sh"'
        )
        lines.append(f"conda activate {params.conda_env}")
        lines.append("")

    if not params.workdir:
        lines.append("cd $SLURM_SUBMIT_DIR")
        lines.append("")

    # ── User commands ──
    lines.append("# ── Commands ──")
    for cmd in params.commands:
        lines.append(cmd)
    lines.append("")

    lines.append('echo "Job $SLURM_JOB_ID finished at $(date)"')
    lines.append("")

    return "\n".join(lines)


def write_script(content: str, path: str) -> str:
    """Write script to file and make it executable. Returns the absolute path."""
    abs_path = os.path.abspath(path)
    with open(abs_path, "w") as f:
        f.write(content)
    os.chmod(abs_path, os.stat(abs_path).st_mode | stat.S_IXUSR | stat.S_IXGRP)
    return abs_path


def preview_script(content: str) -> None:
    """Print the script to stdout with a decorative border."""
    script_lines = content.splitlines()
    width = max((len(line) for line in script_lines), default=40) + 4
    width = min(width, 100)
    bar = "─" * width
    print(f"\n┌{bar}┐")
    for line in script_lines:
        print(f"│ {line:<{width - 2}} │")
    print(f"└{bar}┘")
